name: Build & Deploy Unity WebGL
on:
  push:
    branches:
      - main
      - terraform-deploys
env:
  BUCKET: unitykwhitejrcom-origin
  UNITY_DIR: EventDrivenCharacterController
jobs:
  build:
    name: Build For WebGL Platform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: $UNITY_DIR
    steps:
      - uses: actions/checkout@v2
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
  deploy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: terraform
    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-skip-session-tagging: true
      - name: Deploy static site from public dir to S3 bucket
        run: aws s3 sync ./public s3://$BUCKET --delete
