name: Build & Deploy Unity WebGL
on:
  push:
    branches:
      - main
      - terraform-deploys
env:
  BUCKET: unitykwhitejrcom-origin
jobs:
  deploy:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: terraform
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-skip-session-tagging: true
      - name: Deploy static site from public dir to S3 bucket
        run: aws s3 sync ./public s3://$BUCKET --delete
